name: test and archive

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  run:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: test
        run: ./test/bats/bin/bats test/test.bats
  archive:
    name: archive files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "lwh8762@gmail.com"
          git config --global user.name "lewohy"

      - name: Checkout to archive
        run: |
          git checkout -b archive

      - name: Move script to root
        run: mv ./src/*.sh ./

      - name: Remove all files
        run: |
          git rm -r --cached .
          git clean -f -d

      - name: Add files
        run: |
          git add *.sh README.docs *.txt
          git commit -m "Update archive branch with selected files"

      - name: Push changes
        run: |
          git push origin archive --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
